/**
 * Integration path: processed play → API repository → FastAPI endpoint →
 * web contract. The examples are real responses from the API code over a
 * synthetic dataset (packages/contracts, regenerated by `pnpm contracts:generate`
 * and checked for drift by the API test suite).
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import type { ZodType } from "zod";
import {
  DatasetStatusSchema,
  ErrorEnvelopeSchema,
  FacetsSchema,
  FramesPayloadSchema,
  EvaluationReportSchema,
  FuturePayloadSchema,
  ModelInfoSchema,
  PlayDetailSchema,
  PlayPageSchema,
  TrajectoryPredictionSchema,
} from "@/lib/contracts";
import { buildGroundTruth } from "@/lib/play/groundTruth";
import { parsePlayId } from "@/lib/playId";
import { isFlipped, toDisplay } from "@/lib/tracking/geometry";
import { buildSeries, frameIndexAt } from "@/lib/tracking/series";
import { createClient } from "./index";
import type { RawSource } from "./types";

function example(name: string): unknown {
  return JSON.parse(readFileSync(new URL(`../../../../../packages/contracts/examples/${name}`, import.meta.url), "utf8"));
}

/** Parse, then require the result to equal the input: a missing or unknown field fails. */
function exact<T>(schema: ZodType<T>, name: string): T {
  const raw = example(name);
  const parsed = schema.parse(raw);
  expect(parsed).toEqual(raw);
  return parsed;
}

const exampleSource: RawSource = {
  kind: "api",
  getDataset: async () => example("dataset.json"),
  listPlays: async () => example("play-page.json"),
  getFacets: async () => example("facets.json"),
  getPlay: async () => example("play-detail.json"),
  getFrames: async () => example("frames.json"),
  getFuture: async () => example("future.json"),
  listModels: async () => example("models.json"),
  findSimilar: async () => null,
  compare: async () => null,
  predictTrajectory: async () => null,
  getPlayLabConfig: async () => null,
  runCounterfactual: async () => null,
  getEvaluation: async () => null,
};

describe("API examples match the web contract exactly", () => {
  it("parses every resource without dropping or missing fields", () => {
    exact(DatasetStatusSchema, "dataset.json");
    exact(PlayPageSchema, "play-page.json");
    exact(FacetsSchema, "facets.json");
    exact(PlayDetailSchema, "play-detail.json");
    exact(FramesPayloadSchema, "frames.json");
    exact(FuturePayloadSchema, "future.json");
    exact(ModelInfoSchema.array(), "models.json");
    exact(ModelInfoSchema.array(), "models-empty.json");
    exact(TrajectoryPredictionSchema, "trajectory-prediction.json");
    exact(EvaluationReportSchema, "evaluation-summary.json");
    exact(ErrorEnvelopeSchema, "error-play-not-found.json");
    exact(ErrorEnvelopeSchema, "error-invalid-play-id.json");
    exact(ErrorEnvelopeSchema, "error-model-unavailable.json");
    exact(ErrorEnvelopeSchema, "error-unsupported-origin.json");
  });

  it("keeps list items lightweight and identities unambiguous", () => {
    const page = exact(PlayPageSchema, "play-page.json");
    expect(page.items.length).toBeGreaterThan(0);
    for (const item of page.items) {
      expect(item).not.toHaveProperty("players");
      expect(item.id).toBe(`${item.game_id}-${item.play_id}`);
      expect(parsePlayId(item.id)).toEqual({ gameId: item.game_id, playId: item.play_id });
    }
    expect(page.similarity).toBeNull();
    expect(page.dataset.synthetic).toBe(false);
  });

  it("reports an empty model registry when no artifact exists, and a 503 for forecasts", () => {
    expect(example("models-empty.json")).toEqual([]);
    expect(ErrorEnvelopeSchema.parse(example("error-model-unavailable.json")).error.code).toBe("model_unavailable");
  });

  it("describes a served model with versions and recorded metrics", () => {
    const [m] = ModelInfoSchema.array().parse(example("models.json"));
    expect(m.kind).toBe("learned");
    expect(m.trajectory?.origin).toBe("last_observed_frame");
    expect(m.trajectory?.uncertainty).toBe("none");
    expect(m.provenance?.dataset_version).toMatch(/^nfl_bdb_2026_analytics@full-/);
    expect(m.metrics.map((x) => x.split).sort()).toEqual(["test", "validation"]);
  });

  it("keeps a prediction aligned with output frames and free of fake uncertainty", () => {
    const p = TrajectoryPredictionSchema.parse(example("trajectory-prediction.json"));
    expect(p.future_frame_ids).toEqual(p.players[0].path.map((_, k) => k + 1));
    expect(p.uncertainty.kind).toBe("none");
    expect(p.players.every((x) => x.samples === null && x.valid.length === x.path.length)).toBe(true);
    expect(p.input_window.end_frame_id).toBe(p.origin_frame_id);
  });
});

describe("replay frame conversion from API payloads", () => {
  const client = createClient(exampleSource);

  it("assembles observed frames into an ordered, stable replay series", async () => {
    const detail = await client.getPlay("any");
    const frames = await client.getFrames("any");
    const series = buildSeries(detail, frames);
    expect(series.playId).toBe(detail.id);
    expect(series.frameIds).toEqual(frames.frames.map((f) => f.frame_id));
    expect(series.times).toEqual(frames.frames.map((f) => f.frame_index / detail.frame_rate_hz));
    expect(series.frameIds.length).toBe(detail.tracking.observed_frame_count);
    expect(series.tracks.map((t) => t.ref.player_id)).toEqual(detail.players.map((p) => p.player_id));
    for (const t of series.tracks) for (let i = 0; i < series.times.length; i++) expect(Number.isFinite(t.x[i])).toBe(true);
    // No frame-level ball in this dataset: the series says so instead of inventing one.
    expect(series.ball).toBeNull();
    expect(series.events).toEqual([]);
    expect(series.snapIndex).toBeNull();
    expect(frameIndexAt(series.times, series.times[3] + 0.04)).toBe(3);
  });

  it("serves canonical coordinates that the Source view rotates back to the recorded frame", async () => {
    const detail = await client.getPlay("any");
    const series = buildSeries(detail, await client.getFrames("any"));
    expect(detail.play_direction).toBe("left");
    expect(detail.coordinates.raw_transform).toBe("rotate_180");
    const passer = series.tracks.findIndex((t) => t.ref.role === "Passer");
    expect(series.tracks[passer].x[0]).toBeLessThan(detail.line_of_scrimmage_x!);
    const landing = detail.ball_landing!;
    const recorded = toDisplay(landing.x, landing.y, isFlipped(detail.play_direction, "source"));
    expect(recorded.x).toBeCloseTo(landing.x_raw, 2);
    expect(recorded.y).toBeCloseTo(landing.y_raw, 2);
  });

  it("keeps the held-out future separate and anchors it at the last observed frame", async () => {
    const detail = await client.getPlay("any");
    const series = buildSeries(detail, await client.getFrames("any"));
    const future = await client.getFuture("any");
    const last = series.frameIds.length - 1;
    expect(future.kind).toBe("actual_future");
    expect(future.origin_frame_id).toBe(series.frameIds[last]);
    const targets = detail.players.filter((p) => p.player_to_predict).map((p) => p.player_id);
    expect(future.trajectories.map((t) => t.player_id).sort()).toEqual(targets.sort());
    for (const t of future.trajectories) {
      expect(t.points[0].frame_index).toBe(last + 1);
      expect(t.points.map((p) => p.frame_id)).toEqual(Array.from({ length: future.horizon_frames }, (_, k) => k + 1));
    }
    const gt = buildGroundTruth(series, detail, future, { future: true, landing: true })!;
    expect(gt.paths).toHaveLength(targets.length);
    for (const path of gt.paths) {
      expect(path.from).toEqual({ x: series.tracks[path.playerIndex].x[last], y: series.tracks[path.playerIndex].y[last] });
    }
    expect(gt.landing).toEqual({ x: detail.ball_landing!.x, y: detail.ball_landing!.y });
    expect(buildGroundTruth(series, detail, future, { future: false, landing: false })).toBeNull();
    expect(buildGroundTruth(series, detail, { ...future, id: "other-play" }, { future: true, landing: false })).toBeNull();
  });

  it("handles missing optional metadata as null, never as a default value", () => {
    const raw = example("play-detail.json") as Record<string, unknown>;
    const stripped = {
      ...raw,
      annotations: { ...(raw.annotations as object), coverage_type: null, target_route: null, play_action: null },
      outcome: { ...(raw.outcome as object), pass_result: null, yards_gained: null },
      ball_landing: null,
      description: null,
    };
    const parsed = PlayDetailSchema.parse(stripped);
    expect(parsed.annotations.coverage_type).toBeNull();
    expect(parsed.outcome.yards_gained).toBeNull();
    expect(parsed.ball_landing).toBeNull();
    expect(buildGroundTruth(buildSeries(parsed, FramesPayloadSchema.parse(example("frames.json"))), parsed, undefined, { future: true, landing: true })).toBeNull();
  });
});
